name: CI-PR
on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build
      - working-directory: core
        run: |
          npm run bundle
          npm run bundle:min
          npm run coverage

      - run: npm run doc